server:
  port : 8097
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/finalBack
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: movieQueue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/